# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlwQjEhVxqj4HTx9-HnCLLJaDF9Lsf3J
"""

!pip install scikit-learn seaborn -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import warnings
warnings.filterwarnings('ignore')

# Configure plotting
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("✅ All libraries imported successfully!")
print(f"NumPy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")


PORTFOLIO_SIZE = 100  # Million dollars
CURRENT_NPL = 3.0     # Current NPL ratio (%)
CAPITAL_RATIO = 12.0  # Current capital adequacy ratio (%)

print("\n" + "="*70)
print("BANK PORTFOLIO PARAMETERS")
print("="*70)
print(f"Portfolio Size:        ${PORTFOLIO_SIZE}M")
print(f"Current NPL Ratio:     {CURRENT_NPL}%")
print(f"Current Capital Ratio: {CAPITAL_RATIO}%")

# GENERATE SYNTHETIC HISTORICAL DATA


def generate_historical_data(n_samples=500):
    np.random.seed(42)

    # Macroeconomic factors
    gdp_growth = np.random.normal(2.0, 2.5, n_samples)
    unemployment = np.random.normal(6.0, 2.0, n_samples)
    interest_rate = np.random.normal(4.0, 1.5, n_samples)
    inflation = np.random.normal(3.0, 1.0, n_samples)
    property_prices = np.random.normal(5.0, 8.0, n_samples)
    credit_spread = np.random.normal(2.0, 1.0, n_samples)
    liquidity_index = np.random.normal(50, 15, n_samples)
    loan_growth = np.random.normal(8.0, 5.0, n_samples)
    deposit_growth = np.random.normal(6.0, 4.0, n_samples)

    # Target: NPL ratio with economic relationships
    npl_ratio = (
        3.0
        - 0.3 * gdp_growth
        + 0.4 * unemployment
        + 0.2 * interest_rate
        - 0.1 * property_prices
        + 0.3 * credit_spread
        + np.random.normal(0, 0.5, n_samples)
    )
    npl_ratio = np.clip(npl_ratio, 0.5, 25.0)

    data = pd.DataFrame({
        'gdp_growth': gdp_growth,
        'unemployment': unemployment,
        'interest_rate': interest_rate,
        'inflation': inflation,
        'property_prices': property_prices,
        'credit_spread': credit_spread,
        'liquidity_index': liquidity_index,
        'loan_growth': loan_growth,
        'deposit_growth': deposit_growth,
        'npl_ratio': npl_ratio
    })

    return data

historical_data = generate_historical_data()
print(f"\n✅ Generated {len(historical_data)} historical data points")
print("\nFirst 5 rows:")
display(historical_data.head())
print("\nDescriptive Statistics:")
display(historical_data.describe().round(2))

# ============================================================================
# EXPLORATORY DATA ANALYSIS
# ============================================================================

print("\n" + "="*70)
print("EXPLORATORY DATA ANALYSIS")
print("="*70)

# Correlation heatmap
plt.figure(figsize=(12, 8))
correlation_matrix = historical_data.corr()
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Feature Correlation Matrix', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Distribution plots
fig, axes = plt.subplots(4, 3, figsize=(15, 16)) # Changed from 3,3 to 4,3 to accommodate all 10 columns
axes = axes.ravel()

for idx, column in enumerate(historical_data.columns):
    if idx < len(axes): # Added a check to prevent IndexError if there are more columns than subplots
        axes[idx].hist(historical_data[column], bins=30, edgecolor='black', alpha=0.7)
        axes[idx].set_title(column, fontsize=10, fontweight='bold')
        axes[idx].grid(alpha=0.3)
    else:
        print(f"Warning: Not enough subplots for column '{column}'")

plt.tight_layout()
plt.show()

# ============================================================================
# PREPARE DATA & TRAIN ML MODELS
# ============================================================================

print("\n" + "="*70)
print("TRAINING MACHINE LEARNING MODELS")
print("="*70)

# Prepare data
X = historical_data.drop('npl_ratio', axis=1)
y = historical_data['npl_ratio']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples:  {len(X_test)}")

# Train Random Forest
print("\n1. Training Random Forest...")
rf_model = RandomForestRegressor(
    n_estimators=100, max_depth=10, random_state=42, n_jobs=-1
)
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)

# Train Gradient Boosting
print("2. Training Gradient Boosting...")
gb_model = GradientBoostingRegressor(
    n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42
)
gb_model.fit(X_train_scaled, y_train)
gb_pred = gb_model.predict(X_test_scaled)

print("\n✅ Models trained successfully!")

# Model Evaluation
print("\n" + "="*70)
print("MODEL EVALUATION")
print("="*70)

for name, pred in [('Random Forest', rf_pred), ('Gradient Boosting', gb_pred)]:
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    mae = mean_absolute_error(y_test, pred)
    r2 = r2_score(y_test, pred)

    print(f"\n{name}:")
    print(f"  RMSE: {rmse:.4f}")
    print(f"  MAE:  {mae:.4f}")
    print(f"  R²:   {r2:.4f}")

# Visualization: Actual vs Predicted
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].scatter(y_test, rf_pred, alpha=0.6, edgecolors='black')
axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
             'r--', lw=2, label='Perfect Prediction')
axes[0].set_xlabel('Actual NPL Ratio (%)')
axes[0].set_ylabel('Predicted NPL Ratio (%)')
axes[0].set_title(f'Random Forest (R² = {r2_score(y_test, rf_pred):.3f})', fontweight='bold')
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].scatter(y_test, gb_pred, alpha=0.6, edgecolors='black', color='orange')
axes[1].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
             'r--', lw=2, label='Perfect Prediction')
axes[1].set_xlabel('Actual NPL Ratio (%)')
axes[1].set_ylabel('Predicted NPL Ratio (%)')
axes[1].set_title(f'Gradient Boosting (R² = {r2_score(y_test, gb_pred):.3f})', fontweight='bold')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Feature Importance
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)

print("\n" + "="*70)
print("FEATURE IMPORTANCE")
print("="*70)
display(feature_importance)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance['Feature'], feature_importance['Importance'], color='steelblue')
plt.xlabel('Importance Score', fontsize=12)
plt.title('Feature Importance for NPL Prediction', fontsize=14, fontweight='bold')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# ============================================================================
# DEFINE STRESS SCENARIOS
# ============================================================================

stress_scenarios = {
    'baseline': {
        'name': 'Baseline Scenario',
        'gdp_growth': 2.5, 'unemployment': 5.0, 'interest_rate': 4.0,
        'inflation': 3.0, 'property_prices': 3.0, 'credit_spread': 1.5,
        'liquidity_index': 60, 'loan_growth': 8.0, 'deposit_growth': 6.0
    },
    'moderate': {
        'name': 'Moderate Stress',
        'gdp_growth': -1.0, 'unemployment': 8.0, 'interest_rate': 6.0,
        'inflation': 4.5, 'property_prices': -10.0, 'credit_spread': 3.0,
        'liquidity_index': 40, 'loan_growth': 2.0, 'deposit_growth': 1.0
    },
    'severe': {
        'name': 'Severe Recession',
        'gdp_growth': -3.5, 'unemployment': 12.0, 'interest_rate': 5.5,
        'inflation': 2.0, 'property_prices': -25.0, 'credit_spread': 5.0,
        'liquidity_index': 25, 'loan_growth': -5.0, 'deposit_growth': -3.0
    },
    'credit_crisis': {
        'name': 'Credit Crisis',
        'gdp_growth': -2.5, 'unemployment': 10.0, 'interest_rate': 4.5,
        'inflation': 1.5, 'property_prices': -20.0, 'credit_spread': 6.0,
        'liquidity_index': 20, 'loan_growth': -8.0, 'deposit_growth': -5.0
    }
}

scenarios_df = pd.DataFrame(stress_scenarios).T
print("\n" + "="*70)
print("STRESS TESTING SCENARIOS")
print("="*70)
display(scenarios_df)

# ============================================================================
# RUN STRESS TESTS
# ============================================================================

def predict_stress_impact(scenario_params, model, scaler):
    scenario_df = pd.DataFrame([scenario_params])
    # Drop the 'name' column as it was not used for training the scaler/models
    scenario_for_scaling = scenario_df.drop('name', axis=1)
    scenario_scaled = scaler.transform(scenario_for_scaling)
    predicted_npl = max(model.predict(scenario_scaled)[0], 0.5)

    expected_loss = (PORTFOLIO_SIZE * predicted_npl) / 100
    provisions = (PORTFOLIO_SIZE * predicted_npl * 0.5) / 100

    npl_multiplier = predicted_npl / CURRENT_NPL
    rwa_increase = 1 + (npl_multiplier - 1) * 0.3
    new_rwa = PORTFOLIO_SIZE * 0.8 * rwa_increase

    capital_depletion = expected_loss + provisions * 0.5
    current_capital = (PORTFOLIO_SIZE * CAPITAL_RATIO) / 100
    stressed_capital = current_capital - capital_depletion
    stressed_capital_ratio = (stressed_capital / new_rwa) * 100

    return {
        'predicted_npl': predicted_npl,
        'expected_loss': expected_loss,
        'provisions': provisions,
        'stressed_capital_ratio': stressed_capital_ratio,
        'capital_depletion': capital_depletion,
        'rwa_increase': (rwa_increase - 1) * 100
    }

stress_results = {}

print("\n" + "="*70)
print("STRESS TEST RESULTS")
print("="*70)

for scenario_key, scenario_params in stress_scenarios.items():
    print(f"\n{scenario_params['name']}:")
    print("-"*70)

    rf_results = predict_stress_impact(scenario_params, rf_model, scaler)
    gb_results = predict_stress_impact(scenario_params, gb_model, scaler)

    avg_results = {
        key: (rf_results[key] + gb_results[key]) / 2
        for key in rf_results.keys()
    }

    stress_results[scenario_key] = avg_results

    print(f"  Predicted NPL:       {avg_results['predicted_npl']:>6.2f}%")
    print(f"  Expected Loss:       ${avg_results['expected_loss']:>6.1f}M")
    print(f"  Required Provisions: ${avg_results['provisions']:>6.1f}M")
    print(f"  Capital Ratio:       {avg_results['stressed_capital_ratio']:>6.2f}%")
    print(f"  Capital Depletion:   ${avg_results['capital_depletion']:>6.1f}M")

    if avg_results['stressed_capital_ratio'] >= 8.0:
        print(f"  Status: ✅ PASS (Above 8% minimum)")
    else:
        print(f"  Status: ❌ FAIL (Below 8% minimum)")

# ============================================================================
# COMPREHENSIVE VISUALIZATIONS
# ============================================================================

print("\n" + "="*70)
print("GENERATING VISUALIZATIONS")
print("="*70)

fig = plt.figure(figsize=(16, 12))

scenarios = list(stress_results.keys())
scenario_names = [stress_scenarios[s]['name'] for s in scenarios]

# 1. NPL Ratios
ax1 = plt.subplot(2, 3, 1)
npl_values = [stress_results[s]['predicted_npl'] for s in scenarios]
ax1.bar(scenario_names, npl_values, color=['#2ecc71', '#f39c12', '#e74c3c', '#c0392b'])
ax1.axhline(y=CURRENT_NPL, color='blue', linestyle='--', label='Current', linewidth=2)
ax1.axhline(y=15, color='red', linestyle='--', label='Threshold', linewidth=2)
ax1.set_ylabel('NPL Ratio (%)', fontsize=11)
ax1.set_title('NPL Ratios by Scenario', fontsize=12, fontweight='bold')
ax1.legend()
ax1.grid(axis='y', alpha=0.3)
plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45, ha='right', fontsize=9)

# 2. Capital Adequacy
ax2 = plt.subplot(2, 3, 2)
capital_values = [stress_results[s]['stressed_capital_ratio'] for s in scenarios]
ax2.bar(scenario_names, capital_values, color=['#2ecc71', '#f39c12', '#e74c3c', '#c0392b'])
ax2.axhline(y=8, color='red', linestyle='--', label='Min (8%)', linewidth=2)
ax2.axhline(y=10.5, color='orange', linestyle='--', label='Buffer (10.5%)', linewidth=2)
ax2.axhline(y=CAPITAL_RATIO, color='blue', linestyle='--', label='Current', linewidth=2)
ax2.set_ylabel('Capital Ratio (%)', fontsize=11)
ax2.set_title('Capital Adequacy Under Stress', fontsize=12, fontweight='bold')
ax2.legend(fontsize=8)
ax2.grid(axis='y', alpha=0.3)
plt.setp(ax2.xaxis.get_majorticklabels(), rotation=45, ha='right', fontsize=9)

# 3. Expected Losses
ax3 = plt.subplot(2, 3, 3)
loss_values = [stress_results[s]['expected_loss'] for s in scenarios]
ax3.bar(scenario_names, loss_values, color=['#2ecc71', '#f39c12', '#e74c3c', '#c0392b'])
ax3.set_ylabel('Expected Loss ($M)', fontsize=11)
ax3.set_title('Expected Credit Losses', fontsize=12, fontweight='bold')
ax3.grid(axis='y', alpha=0.3)
plt.setp(ax3.xaxis.get_majorticklabels(), rotation=45, ha='right', fontsize=9)

# 4. Capital Depletion
ax4 = plt.subplot(2, 3, 4)
depletion_values = [stress_results[s]['capital_depletion'] for s in scenarios]
ax4.bar(scenario_names, depletion_values, color=['#2ecc71', '#f39c12', '#e74c3c', '#c0392b'])
ax4.set_ylabel('Capital Depletion ($M)', fontsize=11)
ax4.set_title('Total Capital Impact', fontsize=12, fontweight='bold')
ax4.grid(axis='y', alpha=0.3)
plt.setp(ax4.xaxis.get_majorticklabels(), rotation=45, ha='right', fontsize=9)

# 5. Baseline vs Severe
ax5 = plt.subplot(2, 3, 5)
metrics = ['NPL\nRatio', 'Capital\nRatio', 'Loss']
baseline = [stress_results['baseline']['predicted_npl'],
            stress_results['baseline']['stressed_capital_ratio'],
            stress_results['baseline']['expected_loss']]
severe = [stress_results['severe']['predicted_npl'],
          stress_results['severe']['stressed_capital_ratio'],
          stress_results['severe']['expected_loss']]

x = np.arange(len(metrics))
width = 0.35
ax5.bar(x - width/2, baseline, width, label='Baseline', color='#2ecc71')
ax5.bar(x + width/2, severe, width, label='Severe', color='#e74c3c')
ax5.set_xticks(x)
ax5.set_xticklabels(metrics)
ax5.set_title('Baseline vs Severe', fontsize=12, fontweight='bold')
ax5.legend()
ax5.grid(axis='y', alpha=0.3)

# 6. Summary Table
ax6 = plt.subplot(2, 3, 6)
ax6.axis('off')

summary_data = []
for scenario in scenarios:
    summary_data.append([
        stress_scenarios[scenario]['name'][:15],
        f"{stress_results[scenario]['predicted_npl']:.1f}%",
        f"{stress_results[scenario]['stressed_capital_ratio']:.1f}%",
        f"${stress_results[scenario]['expected_loss']:.1f}M"
    ])

table = ax6.table(cellText=summary_data,
                  colLabels=['Scenario', 'NPL', 'CAR', 'Loss'],
                  cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(9)
table.scale(1, 2)
ax6.set_title('Summary Metrics', fontsize=12, fontweight='bold', pad=20)

plt.tight_layout()
plt.show()

# ============================================================================
# FINAL RECOMMENDATIONS
# ============================================================================

print("\n" + "="*70)
print("RECOMMENDATIONS & INSIGHTS")
print("="*70)

severe_car = stress_results['severe']['stressed_capital_ratio']
severe_loss = stress_results['severe']['expected_loss']

print("\n📊 Key Findings:")
print(f"  • Baseline NPL: {stress_results['baseline']['predicted_npl']:.2f}%")
print(f"  • Severe NPL: {stress_results['severe']['predicted_npl']:.2f}%")
print(f"  • Max Loss: ${max([stress_results[s]['expected_loss'] for s in scenarios]):.1f}M")

print("\n💡 Recommendations:")
if severe_car < 8:
    print("  ⚠️  CRITICAL: Immediate capital raising required")
elif severe_car < 10.5:
    print("  ⚠️  WARNING: Build capital buffer")
else:
    print("  ✅ HEALTHY: Capital position adequate")

print(f"\n  → Recommended provision buffer: ${severe_loss * 1.2:.1f}M")
print(f"  → Suggested capital target: {max(severe_car + 2, 12):.1f}%")

print("\n" + "="*70)
print("✅ STRESS TESTING COMPLETE!")
print("="*70)